### ISSUE TITLE
Build issues with filebox dependency

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis-hello#4]
```
± % make generate build
go generate github.com/owncloud/ocis-hello/pkg/assets
panic: No files found

goroutine 1 [running]:
main.main()
        /home/vincent/go/pkg/mod/github.com/!unno!ted/fileb0x@v1.1.3/main.go:101 +0x26d4
exit status 2
pkg/assets/assets.go:11: running "go": exit status 1
make: *** [Makefile:71: generate] Error 1
```

This is with go1.12-1.12.9-1.1.x86_64 from openSUSE Tumbleweed

**Comment by tboerger** [comment]
I need to extend the README, you got to build the frontend first:

```
yarn install
yarn build

make generate build
```
